spring.application.name=ecom-web
spring.datasource.url=jdbc:mysql://sql10.freesqldatabase.com:3306/sql10828757
spring.datasource.driverClasName=com.mysql.cj.jdbc.Driver
spring.datasource.username=sql10828757
spring.datasource.password =UCsHNUjSJJ

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true








